api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
            versions: [ 3 ]
    formats:
        json: [ 'application/json' ]
    patch_formats:
        json: ['application/json']

